// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARpQ1FQUfHnvNcBqr_l-xUBa_kOptNnWc',
    appId: '1:956551233387:web:c593fb212d2b6e44ea962e',
    messagingSenderId: '956551233387',
    projectId: 'agrinexa-ad9de',
    authDomain: 'agrinexa-ad9de.firebaseapp.com',
    storageBucket: 'agrinexa-ad9de.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2VP_AeLIxFarZE_lmZgSicV6Nr3-H2p4',
    appId: '1:956551233387:android:04da86707adfe06bea962e',
    messagingSenderId: '956551233387',
    projectId: 'agrinexa-ad9de',
    storageBucket: 'agrinexa-ad9de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg8iJ6on_nrAfRoDEEOK00Ceku4VXsL3w',
    appId: '1:956551233387:ios:ecebc066a14f5cf2ea962e',
    messagingSenderId: '956551233387',
    projectId: 'agrinexa-ad9de',
    storageBucket: 'agrinexa-ad9de.firebasestorage.app',
    iosBundleId: 'com.example.agrinexa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAg8iJ6on_nrAfRoDEEOK00Ceku4VXsL3w',
    appId: '1:956551233387:ios:ecebc066a14f5cf2ea962e',
    messagingSenderId: '956551233387',
    projectId: 'agrinexa-ad9de',
    storageBucket: 'agrinexa-ad9de.firebasestorage.app',
    iosBundleId: 'com.example.agrinexa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARpQ1FQUfHnvNcBqr_l-xUBa_kOptNnWc',
    appId: '1:956551233387:web:81e614f1bb38ce9eea962e',
    messagingSenderId: '956551233387',
    projectId: 'agrinexa-ad9de',
    authDomain: 'agrinexa-ad9de.firebaseapp.com',
    storageBucket: 'agrinexa-ad9de.firebasestorage.app',
  );
}
